import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const googleSansDisplayRegular = localFont({
  src: "../lib/fonts/GoogleSansDisplay-Regular.ttf",
  variable: "--font-googlesansdisplay-regular",
  display: "swap",
});

const googleSansDisplayBold = localFont({
  src: "../lib/fonts/GoogleSansDisplay-Bold.ttf",
  variable: "--font-googlesansdisplay-bold",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Google Developer Group Portlaoise",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${googleSansDisplayRegular.variable} ${googleSansDisplayBold.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
